### PR TITLE
move healthz handler

### PR DESCRIPTION
**Pull request by thecrogers**
This PR is to address a problem with a memory leak. This leak was found after looking though our Go services with Matt. It was determined that the user service was using an old version of json-api, and  had normal memory usage. Several other go services were more up to date, and where experiencing memory leaks.  After digging into json-api, it was determined that this healthz handler was being added for every http request.

### CODE REVIEW

**Comment by MDrollette** [comment]
Can you confirm that this change 1. still works for health checks and 2. fixes the mem leak problem?

**Comment by thecrogers** [comment]
Health check still functions, product service is up in staging at the moment. Not a very easy way to determine if the mem leak is fixed, as it took days for the memory to build up. My thought is we leave this in a PR. Add this json-api version to one service, and watch it over the next few days.

**Comment by PRAgarawal** [comment]
A thought: I'm curious how you determined that this might be the cause of the memory leak. Would it make sense for a brief summary of that kind of thing to be included in the description for a pull request like this?

**Comment by thecrogers** [comment]
@PRAgarawal good call I will write something up.

**Comment by thecrogers** [comment]
results on product service from this fix. 
mem stats for 11K request  on old product service. 
screen shot 2017-08-31 at 11 15 53 am

With Fix
screen shot 2017-08-31 at 11 21 25 am

If you are interested in the graphs let me know and I will send them to you.

**Pull request merged**
